name: flutil
author: Gabriel Soares <soaresggm@gmail.com>
homepage: https://github.com/gosoares/flutil
description: Flutter Utilities
version: 0.0.3

environment:
  sdk: ">=2.0.0-dev.35 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  rxdart: ^0.26.0
  connectivity: ^3.0.3